{"name": "Ошибка при неверном ID курьера", "status": "passed", "statusDetails": {"message": "XPASS API возвращает 500 вместо 404"}, "steps": [{"name": "Получить заказ по треку №172704", "status": "passed", "parameters": [{"name": "track", "value": "172704"}], "start": 1745144617496, "stop": 1745144617583}, {"name": "Принять заказ №453816 курьером 'invalid_courier_id'", "status": "passed", "parameters": [{"name": "order_id", "value": "453816"}, {"name": "courier_id", "value": "'invalid_courier_id'"}], "start": 1745144617584, "stop": 1745144617612}], "attachments": [{"name": "log", "source": "6371c4e6-e34a-47e2-ba58-6b55ab8d9de7-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "0fbfb7af-e2bd-4cd4-826e-e5414a729c77-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "08fa7dc6-95fe-4705-be6e-3826f5a25c92-attachment.txt", "type": "text/plain"}], "start": 1745144617496, "stop": 1745144617613, "uuid": "c1e1c016-e823-43cd-88f6-74f2af090bdc", "historyId": "32c9abb9e238f9170f6964d25ca2b702", "testCaseId": "32c9abb9e238f9170f6964d25ca2b702", "fullName": "tests.test_order.TestOrderAcceptance#test_accept_order_invalid_courier_id", "labels": [{"name": "feature", "value": "Принятие заказов"}, {"name": "tag", "value": "@pytest.mark.xfail(reason='API возвращает 500 вместо 404')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order"}, {"name": "subSuite", "value": "TestOrderAcceptance"}, {"name": "host", "value": "Gemini_78"}, {"name": "thread", "value": "17288-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order"}]}