{"name": "Ошибка при неверном ID заказа", "status": "passed", "statusDetails": {"message": "XPASS API возвращает 500 вместо 404"}, "steps": [{"name": "Принять заказ №999999 курьером 507932", "status": "passed", "parameters": [{"name": "order_id", "value": "999999"}, {"name": "courier_id", "value": "507932"}], "start": 1745261086766, "stop": 1745261086804}], "attachments": [{"name": "log", "source": "a6da05f4-9530-462b-9924-96bb90b90b58-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "48e9cc29-f290-4966-ab55-f21943bbc7f8-attachment.txt", "type": "text/plain"}], "start": 1745261086766, "stop": 1745261086804, "uuid": "f6df70d2-75c9-4fbe-9aad-aefbc0b3afc3", "historyId": "0045170f006f8e281a3b96222e577171", "testCaseId": "0045170f006f8e281a3b96222e577171", "fullName": "tests.test_order.TestOrderAcceptance#test_accept_order_invalid_order_id", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(reason='API возвращает 500 вместо 404')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order"}, {"name": "subSuite", "value": "TestOrderAcceptance"}, {"name": "host", "value": "Gemini_78"}, {"name": "thread", "value": "2332-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order"}]}